export const TEMPLATES = [
    {
        id: "geometric",
        name: "Geometric Resume",
        description: "Modern layout with colorful geometric shapes and clean structure.",
        image: "https://images.unsplash.com/photo-1586281380349-632531db7ed4?auto=format&fit=crop&q=80&w=400",
        tags: ["Geometric", "Creative", "Modern"],
    },
    {
        id: "impact",
        name: "Impact Resume",
        description: "Professional sidebar layout with high-impact typography and teal accents.",
        image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400",
        tags: ["Sidebar", "Professional", "Teal"],
    },
    {
        id: "modern-basic",
        name: "Basic Modern Resume",
        description: "Clean, centered design with blue accents for a traditional professional look.",
        image: "https://images.unsplash.com/photo-1512485694743-9c9538b4e6e0?auto=format&fit=crop&q=80&w=400",
        tags: ["Centered", "Blue", "Classic"],
    },
    {
        id: "clean-elegant",
        name: "Clean Elegant Resume",
        description: "Sophisticated two-column layout with a soft blue background and minimal lines.",
        image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&q=80&w=400",
        tags: ["Two-Column", "Elegant", "Clean"],
    },
    {
        id: "bold-executive",
        name: "Bold Executive Resume",
        description: "Authoritative design with a prominent dark header block and high contrast.",
        image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=80&w=400",
        tags: ["Bold", "Executive", "High-Contrast"],
    },
    {
        id: "triple-block",
        name: "Triple-Block Resume",
        description: "Unique grid-based layout with dark blocks and teal highlights (Ian Hansson style).",
        image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=400",
        tags: ["Grid", "Dark-Mode", "Tech"],
    },
    {
        id: "social-clean",
        name: "Social Clean Resume",
        description: "Minimalist and airy design perfect for social media, marketing, and creative roles.",
        image: "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?auto=format&fit=crop&q=80&w=400",
        tags: ["Minimal", "Centered", "Modern"],
    },
    {
        id: "vibrant-yellow",
        name: "Vibrant Yellow Resume",
        description: "Bold and energetic design with a full-color background and strong black accents.",
        image: "https://images.unsplash.com/photo-1454165833762-01d0bf7e7a0e?auto=format&fit=crop&q=80&w=400",
        tags: ["Colorful", "Bold", "Impactful"],
    },
    {
        id: "tech-spec",
        name: "Tech Specialist",
        description: "Optimized for developers with a dark theme and code-inspired layout.",
        image: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&q=80&w=400",
        tags: ["Software", "Projects", "Dark-Mode"],
    },
    {
        id: "architect",
        name: "The Architect",
        description: "Geometric layout focusing on grids and structured vertical lines.",
        image: "https://images.unsplash.com/photo-1487958449913-d957d6961246?auto=format&fit=crop&q=80&w=400",
        tags: ["Geometric", "Grid", "Structured"],
    },
];
